### Direct Forwarder configuration ###
[global]
# Домен для подключения
domain = "domain.com"
# Стандартный порт подключения.
#По нему плагин пытается подключиться к домену (например, test.domain.com:25565)."
port = "25565"

[messages]
# Префикс. Он появляется перед всеми сообщениями для игроков.
prefix = "§6DF §8>> §f"
# Сообщения для сконфигурированных серверов
teleport = "§aВы были успешно перенесены на сервер {server}"
errorteleport = "§cПри переносе вас на сервер {server} произошла ошибка: {error}"
# Сообщения при прямом перемещении (если сервер не был сконфигурирован).
directteleport = "§aВы были успешно перенесены на сервер {server} ({domain})."
errordirectteleport = "§cПри переносе вас на сервер {server} ({domain}) произошла ошибка: {error}"